class_name Subtitles
extends Label

## Speech, as text, because there is no recorded speech in this game.
##
## Everything the game makes a noise with is generated by a script in this
## repository (`tools/audio/`), and a script cannot generate a performance.
## Emil's lines are the one place that matters -- `STORY.md` builds the whole
## arc towards a voice on an intercom -- so rather than ship a synthesised
## reading of them, they are subtitles over the sound of the channel being open.
## See `DECISIONS.md` D27.
##
## Which means this is not an accessibility afterthought. It is how the game
## speaks, and the `Subtitle size` setting has been waiting for it.

signal finished

## How long a line stays up, before the per-character part. Short lines still
## need reading time; long ones need more than a fixed number.
@export_range(0.4, 6.0, 0.1) var base_seconds: float = 1.1
@export_range(0.005, 0.2, 0.005) var seconds_per_character: float = 0.045

## Between one line and the next, with nothing on screen. A beat, not a gap:
## it is what makes four sentences read as four sentences.
@export_range(0.0, 3.0, 0.05) var between_seconds: float = 0.55

const SIZES := [17, 21, 26, 32]

var _queue: Array[String] = []
var _left := 0.0
var _gap := 0.0
var _size_choice := 1


func _ready() -> void:
	text = ""
	visible = false
	set_process(false)
	horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vertical_alignment = VERTICAL_ALIGNMENT_BOTTOM
	autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_apply_size()


## Queues lines. Speaking again while something is up replaces what is left,
## rather than interleaving: two people talking over each other is a thing this
## game does not have, and a queue that grew without bound would be a bug.
func say(lines: Array[String]) -> void:
	_queue = lines.duplicate()
	_left = 0.0
	_gap = 0.0
	set_process(true)
	_next()


func clear() -> void:
	_queue.clear()
	text = ""
	visible = false
	set_process(false)


func speaking() -> bool:
	return visible or not _queue.is_empty()


func on_setting(key: StringName, value: float) -> void:
	if key != &"subtitle_size":
		return
	_size_choice = clampi(int(round(value)), 0, SIZES.size() - 1)
	_apply_size()


func _process(delta: float) -> void:
	if _gap > 0.0:
		_gap -= delta
		if _gap <= 0.0:
			_next()
		return
	_left -= delta
	if _left > 0.0:
		return
	text = ""
	visible = false
	if _queue.is_empty():
		set_process(false)
		finished.emit()
		return
	_gap = between_seconds


func _next() -> void:
	if _queue.is_empty():
		set_process(false)
		visible = false
		finished.emit()
		return
	var line: String = _queue.pop_front()
	text = line
	visible = true
	_left = base_seconds + float(line.length()) * seconds_per_character


func _apply_size() -> void:
	add_theme_font_size_override("font_size", SIZES[_size_choice])
