class_name DocumentIndex
extends Resource

## Every document in the game, in story order.
##
## The journal saves ids, because ids are small and stable and a save should not
## carry a copy of the text. Which means after a reload it knows twenty-nine ids
## and cannot show one of them -- and a game whose whole design is that reading
## the documents is how you get out ought to let you read them twice.
##
## Generated by `tools/gen/make_doc_index.py` from what is on disk, and checked
## by the suite against what is on disk. A document that exists and is not in
## here is a document the player can find once and then lose.

@export var documents: Array[Document] = []


func find(id: StringName) -> Document:
	for document in documents:
		if document != null and document.id == id:
			return document
	return null


func count() -> int:
	return documents.size()
